name: Nekomata-ui Codecov code coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/nekomata-ui
    name: Setup Node and Run tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.10'
          cache: 'npm'
      - run: npm install
      - run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
